export default {
  status: ['Disabled', 'Active'],
  data: [
    {
      id: 1,
      name: 'Dorothea Setch',
      email: 'dsetch0@drupal.org',
      status: 1,
      group: 0,
      created_on: '27/09/2020',
    },
    {
      id: 2,
      name: 'Abbe Gouth',
      email: 'ogouth1@home.pl',
      status: 0,
      group: 0,
      created_on: '02/10/2020',
    },
    {
      id: 3,
      name: 'Zelma Cearley',
      email: 'zcearly@unblog.fr',
      status: 1,
      group: 1,
      created_on: '22/06/2020',
    },
    {
      id: 4,
      name: 'Lemmie Palley',
      email: 'lpalley3@hc360.com',
      status: 0,
      group: 2,
      created_on: '14/10/2020',
    },
    {
      id: 5,
      name: 'Demott Bonass',
      email: 'dbonass4@com.com',
      status: 0,
      group: 0,
      created_on: '15/10/2020',
    },
  ],
}
